interface Env {
  WEBHOOK_SECRET: string;
  GOOGLE_GENERATIVE_AI_API_KEY: string;
  RESEND_API_KEY: string;
  POLAR_ACCESS_TOKEN: string;
  POLAR_PRICE_STARTER: string;
  POLAR_PRICE_BUSINESS: string;
  POLAR_PRICE_ENTERPRISE: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  AUTH_GOOGLE_ID: string;
  AUTH_GOOGLE_SECRET: string;
  AUTH_GITHUB_ID: string;
  AUTH_GITHUB_SECRET: string;
}

const env: Env = {
  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET!,
  GOOGLE_GENERATIVE_AI_API_KEY: process.env.GOOGLE_GENERATIVE_AI_API_KEY!,
  RESEND_API_KEY: process.env.RESEND_API_KEY!,

  // POLAR
  POLAR_ACCESS_TOKEN: process.env.POLAR_ACCESS_TOKEN!,

  POLAR_PRICE_STARTER: process.env.POLAR_PRICE_STARTER!,
  POLAR_PRICE_BUSINESS: process.env.POLAR_PRICE_BUSINESS!,
  POLAR_PRICE_ENTERPRISE: process.env.POLAR_PRICE_ENTERPRISE!,

  // BETTER AUTH
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET!,
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL!,

  // SOCIAL AUTH 
  AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID!,
  AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET!,
  AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID!,
  AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET!,
};

export default env;
